export { default as Main } from './main';
export { default as Home } from './home';
export { default as Login } from './login/Login';
export { default as Logout } from './login/Logout';
export { default as Join } from './login/Join';
export { default as Community } from './community';
export { default as Mypage } from './mypage';
export { default as Notfile } from './notfile';
export { default as Video } from './video';
